---
- name: Create system acme group
  become: true
  ansible.builtin.group:
    name: "{{ acme_group }}"
    state: present
    system: true

- name: Create system acme user
  become: true
  ansible.builtin.user:
    name: "{{ acme_user }}"
    state: present
    system: true
    create_home: true
    skeleton: false
    home: "{{ acme_home }}"
    shell: "{{ acme_shell }}"
    group: "{{ acme_group }}"

- name: Ensure required packages are installed
  become: true
  ansible.builtin.apt:
    name: "{{ acmesh_req_packages }}"
    state: present
